### ISSUE TITLE
Reproducing on Tanks and Temples dataset

### ISSUE THREAD

**Issue by zvict** [princeton-vl/SNP#1]
Hi,

Thanks for sharing the code!

I'm trying to reproduce the reported numbers on the Tanks and Temples dataset. Is it possible for you to share the configs for the tanks and temples dataset or even the pre-trained models? That would be very helpful!

Thanks in advance!

**Comment by zuoym15** [comment]
Hi,

Thank you for your interest in our work! I'm currently working on cleaning up the code for NeRF-Synthetic and Tanks&Temples datasets. Hopefully I will update the code before the ICLR conference.

**Comment by zvict** [comment]
Thanks for the reply and effort!

**Comment by zvict** [comment]
Hi, any update on this? Thanks!

**Comment by zuoym15** [comment]
I just updated the instructions for running our pretrained model on the TNT dataset.

**Comment by zvict** [comment]
Great, thanks!
